import type { Metadata } from 'next';
import localFont from 'next/font/local';
import './globals.css';
import NavDropdown from '@/components/NavDropdown';

export const metadata: Metadata = {
	title: 'Against The Storm Explorer',
	description: 'Generated by create next app'
};

export default function RootLayout({
	children
}: Readonly<{
	children: React.ReactNode;
}>)
{
	return (
		<html lang='en'>
			<body className='h-dvh w-dvw overflow-hidden'>
				<div className='w-full flex flex-row items-center justify-between min-h-12 bg-slate-800 px-4'>
					<NavDropdown />
					<div className='flex flex-row items-center'>
						<p className='text-xl text-color-tan'>Against The Storm Explorer</p>
						<sup className='text-perk-orange'>V2</sup>
					</div>
					<div>
						settings here
					</div>
				</div>
				{children}
			</body>
		</html>
	);
}
