import type { Metadata } from 'next';
import localFont from 'next/font/local';
import './globals.css';
import NavDropdown from '@/components/NavDropdown';
import SettingsDropdown from '@/components/SettingsDropdown';
import RootLayoutInner from '@/components/Layout/RootLayoutInner';

export const metadata: Metadata = {
	title: 'Against The Storm Explorer',
	description: 'Generated by create next app'
};

export default function RootLayout({
	children
}: Readonly<{
	children: React.ReactNode;
}>)
{
	return (
		<html lang='en'>
			<RootLayoutInner>
				{children}
			</RootLayoutInner>
		</html>
	);
}
